In [1]:
import torch
from torch.nn import Linear


In [2]:
w=torch.tensor(3.0,requires_grad=True)

b=torch.tensor(1.0,requires_grad=True)


In [3]:
def forward(x):
  y= w * x + b
  return y


In [5]:
# x=torch.tensor(2)
# forward(x)
# can calculate for multiple x values
x=torch.tensor([[2],[3]])
forward(x)


tensor([[ 7.],
        [10.]], grad_fn=<AddBackward0>)

In [7]:
torch.manual_seed(1)
model=Linear(in_features=1,out_features=1)
print(model.weight,model.bias)

Parameter containing:
tensor([[0.5153]], requires_grad=True) Parameter containing:
tensor([-0.4414], requires_grad=True)


In [9]:
x=torch.tensor([2.0])
x=torch.tensor([[2.0],[4.0]])

print(model(x))

tensor([[0.5891],
        [1.6197]], grad_fn=<AddmmBackward0>)
