In [ ]:
!pip3 install torch

In [ ]:
import torch

In [ ]:
v=torch.tensor([1,2,3,4,5,6,7,7,8])
print(v)

tensor([1, 2, 3, 4, 5, 6, 7, 7, 8])


In [ ]:
v.dtype

torch.int64

In [ ]:
v.view

<function Tensor.view>

In [ ]:
f=torch.FloatTensor([1,2,3,4,5,6,7,7,8,9,10])
print(f)

f.size()

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  7.,  8.,  9., 10.])


torch.Size([11])

In [ ]:
g=torch.arange(18).view(3,3,2)
print(g)

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])


In [ ]:
g[1:,:,1:]

tensor([[[ 7],
         [ 9],
         [11]],

        [[13],
         [15],
         [17]]])

In [ ]:
x=torch.tensor([[0,3,5],[5,5,2]])
y=torch.tensor([[3,4],
                [3,-2],
                [4,-2]])


In [ ]:
x@y

tensor([[ 29, -16],
        [ 38,   6]])

In [ ]:
torch.matmul(x,y)

tensor([[ 29, -16],
        [ 38,   6]])

In [ ]:
#  derivation like slope of the function at x=2 can be found in this way
x=torch.tensor(2.0,requires_grad=True)
y= 9*x**4 + 2*x**3+3*x**2+6*x+1
y.backward()
x.grad

tensor(330.)

In [ ]:
# give y=x**2 +z**3 let partially differentiate it using tensor
# to find f'(x,z)=f'(1,2) =(2x)(with respect to x) +(3z**2)(with respect to z)
x=torch.tensor(1.0,requires_grad=True)
z=torch.tensor(2.0,requires_grad=True)

y=x**2 +z**3
y.backward()
print(x.grad)
print(z.grad)


tensor(2.)
tensor(12.)


In [ ]:
import torch
x=torch.rand(24,224,3)
x.shape

torch.Size([24, 224, 3])

In [ ]:
x_changed=x.permute(2,0,1)
x_changed.shape

torch.Size([3, 24, 224])

In [ ]:
x_unsquessd=x.unsqueeze(dim=0)
x_unsquessd.shape

torch.Size([1, 24, 224, 3])

In [ ]:
x_squessd=x_unsquessd.squeeze()
x_squessd.shape

torch.Size([24, 224, 3])

In [ ]:
x=torch.arange(1,5).reshape(1,2,2)
x

tensor([[[1, 2],
         [3, 4]]])

In [ ]:
x.shape

torch.Size([1, 2, 2])

In [ ]:
x[0][:][0][0]

tensor(1)

In [ ]:
y=torch.arange(1,31).reshape(5,6,1)
y

tensor([[[ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6]],

        [[ 7],
         [ 8],
         [ 9],
         [10],
         [11],
         [12]],

        [[13],
         [14],
         [15],
         [16],
         [17],
         [18]],

        [[19],
         [20],
         [21],
         [22],
         [23],
         [24]],

        [[25],
         [26],
         [27],
         [28],
         [29],
         [30]]])

In [ ]:
y[2][4][0]

tensor(17)

In [ ]:
#  use next(model.parameters()).device
#  to get the device on which our model is currently on
#  use the .to(device) to convert tensor on gpu or the targeted device
